group_by_length: True
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
evaluation_strategy: "steps"
save_strategy: "steps"
save_steps: 500
save_total_limit: 2
eval_steps: 500
max_steps: 30000
fp16: True
fp16_full_eval: True
logging_steps: 10
learning_rate: 2e-4
warmup_steps: 500
do_train: True
do_eval: True
do_predict: True
metric_for_best_model: "wer"
greater_is_better: False
seed: 42
