lm_name: microsoft/infoxlm-base
lm_attn_size: 100
sm_attn_size: 499
lm_feat_size: 768
sm_feat_size: 1024

attn_loss: 0.0
feat_loss: 0.25

# w2v2: 25, infoxlm-base: 13
name: interpolate_v2_linear_nonfilter
feat_target:
  - lm_index: 12
    sm_index: 24

# feature interpolation
interpolation:
  mode: linear  # nearest, linear
  filter_out_pad: False
